import {
    SiHtml5,
    SiCss3,  
    SiBootstrap,
    SiReact,
    SiPython,
    SiDjango,
    SiJira,
    SiSalesforce,
    SiPostgresql,
    SiStripe,
    SiSupabase,
    SiFigma,
    SiZapier,
    SiNextdotjs,
    SiNodedotjs,
    SiJavascript,
    SiGooglemaps,
    SiSendgrid,
    SiChartdotjs,
    SiNotion,
    SiAmazoncloudwatch,
    SiAwslambda,
    SiXml,
    SiOpenai,
    SiTailwindcss,
    SiRedux,
    SiMongodb
} from "react-icons/si";
import { FaAws, FaMicrosoft } from "react-icons/fa"

export const ICON_MAP = {
    postgresql: SiPostgresql,
    javascript:   SiJavascript,
    aws:          FaAws,  
    react:        SiReact,
    python:       SiPython,
    django:       SiDjango,
    jira:         SiJira,
    salesforce:   SiSalesforce,
    stripe:       SiStripe,
    supabase:     SiSupabase,
    figma:        SiFigma,
    zapier:       SiZapier,
    nextjs:       SiNextdotjs,
    html5:        SiHtml5,
    css3:      SiCss3,
    bootstrap: SiBootstrap,
    nodejs: SiNodedotjs,
    googlemaps: SiGooglemaps,
    sendgrid: SiSendgrid,
    chartjs: SiChartdotjs,
    notion: SiNotion,
    awslambda: SiAwslambda,
    cloudwatch: SiAmazoncloudwatch,
    xml: SiXml,
    openai: SiOpenai,
    tailwindcss: SiTailwindcss,
    redux: SiRedux,
    mongodb: SiMongodb,
    
    };